print("hello")
name =input ("what is your name?")
print ("hello " + name + ".")
city =input ("where do you live?")
restaurant =input ("what is your favourite restaurant in " + city + "? ")
starter =input ("what starter do you go for?")
main =input("what is your favourite main course?")
desert =input("what about a desert?")
drink =input ("what do you drink with your meal?")
print("your favourite meal is " + starter + ", " + main + ", " + desert + " with " + drink + " at " + restaurant + ".")